[package]
name = "display_macro"
description = "Like print! macro but always flushing"
version = "0.1.1"
edition = "2021"
license = "MIT"
homepage = "https://github.com/dgellow/display-macro-rs"

[dependencies]
